apiVersion: v1
kind: Pod
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  containers:
    - name: spring-boot-app
      image: 172499763739.dkr.ecr.ap-south-1.amazonaws.com/java-poc:latest
      ports:
        - containerPort: 8080
        # service type loadbalancers
---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-app
spec:
  selector:
    app: spring-boot-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer  
