apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: 172499763739.dkr.ecr.ap-south-1.amazonaws.com/java-poc:latest  template:

        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancers
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-svc
spec:
  selector:
    app: spring-boot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
